### ISSUE TITLE
`SlackClient.api_call` error responses are not logged

### ISSUE THREAD

**Issue by alexander-matsievsky** [scrapinghub/spidermon#207]
@jesuslosada @rennerocha Hi, Spidermon team!

Recently I started to get these errors in my job logs:

```
======================================================================
ERROR: SendSlackMessageSpiderFinished
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/python/lib/python3.6/site-packages/spidermon/core/actions.py", line 37, in run
    self.run_action()
  File "/app/python/lib/python3.6/site-packages/spidermon/contrib/actions/slack/__init__.py", line 213, in run_action
    attachments=self.get_attachments(),
  File "/app/python/lib/python3.6/site-packages/spidermon/contrib/actions/slack/__init__.py", line 58, in send_message
    for recipient in to
  File "/app/python/lib/python3.6/site-packages/spidermon/contrib/actions/slack/__init__.py", line 58, in <listcomp>
    for recipient in to
  File "/app/python/lib/python3.6/site-packages/spidermon/contrib/actions/slack/__init__.py", line 79, in send_message
    attachments=attachments,
  File "/app/python/lib/python3.6/site-packages/spidermon/contrib/actions/slack/__init__.py", line 129, in _send_channel_message
    icon_url=self.users[self.sender_name]["profile"]["image_48"],
  File "/app/python/lib/python3.6/site-packages/spidermon/contrib/actions/slack/__init__.py", line 36, in users
    self._users = self._get_users_info()
  File "/app/python/lib/python3.6/site-packages/spidermon/contrib/actions/slack/__init__.py", line 91, in _get_users_info
    for member in self._api_call("users.list")["members"]
KeyError: 'members'
```

From the looks of it, they are caused by the transient Slack API error responses, in my case to the https://api.slack.com/methods/users.list method.

1. Could we log `ok=false` responses?
2. Could we retry such responses several times as they seem to be retryable?

**Comment by alexander-matsievsky** [comment]
In fact, that might be the cause:

> Clients should not send more than one message per second sustained. If you do you may receive an error message or be disconnected.

https://api.slack.com/rtm#errors

**Comment by alexander-matsievsky** [comment]
I've started to receive these errors this week when I automatically scheduled around 15 jobs instantly. Then, `SPIDERMON_PERIODIC_MONITORS` chimed in emitting 15 alerts every 3 hours within the same minute or so. That's a plausible explanation.
