### ISSUE TITLE
Adding new JSON schema format validators

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/spidermon#51]
We're exporting to SQL and having `datetime` objects in the data is the easiest way to send SQL datetimes, but these are rejected by jsonschema.  There's no way to set a validator class or pass extra arguments to the current validator class to override the datetime validator AFAICT.

**Comment by manycoding** [comment]
@andrewbaxter Could you elaborate?
`"format": "date-time"` is probably what you need.

The JSON schema standard supports `formats` and the library used here requires additional dependencies to make them work - jsonschema[formats], see here https://github.com/Julian/jsonschema/blob/master/docs/validate.rst#validating-formats

And there's an official standard https://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3

Just to say, there's `fastjsonschema` which has format validation by default without additional tweaks.

**Comment by Gallaecio** [comment]
@andrewbaxter Should we close this then?

**Comment by andrewbaxter** [comment]
Sorry for the delay - @manycoding and thanks for pinging me @Gallaecio .

I tried "format": "date-time" and it doesn't seem to do anything, ex:
Schema:
```
 {
   "$schema": "http://json-schema.org/draft-04/schema#",
   "type": "object",
   "properties": {
     "v": {
       "type": "string",
       "format": "date-time"
     }
   }
 }
```

Shows:
```
2019-04-05 20:33:27 [scrapy.core.scraper] DEBUG: Scraped from <200 https://scrapinghub.com/>
{'v': 4, '_validation': defaultdict(<class 'list'>, {'v': ['Invalid string']})}
2019-04-05 20:33:27 [scrapy.core.scraper] DEBUG: Scraped from <200 https://scrapinghub.com/>
{'v': 'hi'}
```
The first just to show that validation is happening.  TBH I'm not sure I did that correctly, but if this worked I think that would be very close to what I want.

To clarify on this though, even if Spidermon supports the builtin datetime there are still a lot of types that that are not supported:
```
        yield {
            'v': arrow.now(),
        }
        yield {
            'f': decimal.Decimal('1.03'),
        }
        yield {
            'u': uuid.uuid4(),
        }
```

results in
```
2019-04-05 20:38:20 [scrapy.core.scraper] ERROR: Error processing {'v': <Arrow [2019-04-05T20:38:20.617099+09:00]>}
Traceback (most recent call last):
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/spidermon/contrib/scrapy/pipelines.py", line 119, in process_item
    data = self._convert_item_to_dict(item)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/spidermon/contrib/scrapy/pipelines.py", line 139, in _convert_item_to_dict
    exporter.export_item(item)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/exporters.py", line 93, in export_item
    data = self.encoder.encode(itemdict) + '\n'
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/utils/serialize.py", line 36, in default
    return super(ScrapyJSONEncoder, self).default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Arrow' is not JSON serializable
2019-04-05 20:38:20 [scrapy.core.scraper] DEBUG: Scraped from <200 https://scrapinghub.com/>
{'f': Decimal('1.03'), '_validation': defaultdict(<class 'list'>, {'f': ['Invalid number']})}
2019-04-05 20:38:20 [scrapy.core.scraper] ERROR: Error processing {'u': UUID('12ac80d6-7d50-46a1-bcc5-084f526b9b3b')}
Traceback (most recent call last):
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/spidermon/contrib/scrapy/pipelines.py", line 119, in process_item
    data = self._convert_item_to_dict(item)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/spidermon/contrib/scrapy/pipelines.py", line 139, in _convert_item_to_dict
    exporter.export_item(item)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/exporters.py", line 93, in export_item
    data = self.encoder.encode(itemdict) + '\n'
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/andrew/scraping/temp/30/env/lib/python3.6/site-packages/scrapy/utils/serialize.py", line 36, in default
    return super(ScrapyJSONEncoder, self).default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'UUID' is not JSON serializable
```

(actually I'm not sure why the Decimal example fails)

It's possible to support other non natively jsonifiable types or force specific Python types with jsonschema with code like:
```
import arrow
import jsonschema
import jsonschema.validators


def is_arrow(checker, instance):
    return isinstance(instance, arrow.Arrow)


type_checker = jsonschema.Draft4Validator.TYPE_CHECKER.redefine(
    "datetime", is_arrow)

CustomValidator = jsonschema.validators.extend(
    jsonschema.Draft4Validator, type_checker=type_checker)

print(CustomValidator(
    schema={
        'type': 'object',
        'properties': {
            'v': {
                'type': 'datetime',
            },
        },
    },
).validate(
    instance={'v': arrow.now()},
))
```

**Comment by rendaw** [comment]
Maybe `schematics` should be recommended if you have custom types?  I haven't tried it out though and I felt it was easier to get tight schemas with jsonschema than say marshmallow which I've used before.

**Comment by manycoding** [comment]
@andrewbaxter 
Have you checked that `strict-rfc3339` is installed?

I see that we use old format class https://github.com/scrapinghub/spidermon/blob/e4a5f9f6a97a54c4adefa3c5e2844cc6c96bd7c2/spidermon/contrib/validation/jsonschema/formats.py#L22 but I think it still works in 3.1
https://python-jsonschema.readthedocs.io/en/v2.6.0/validate/

>It's possible to support other non natively jsonifiable types or force specific Python types with jsonschema with code like:
I think it's not possible since you have to modify spidermon code, but that could be a nice feature.
And if you don't want to create customer formats (to keep schema consistent across different project, like Arche and Spidermon), I think you can define your format in the schema with `definitions`

{
   "$schema": "http://json-schema.org/draft-07/schema#",
   "definitions": {"uuid": {"pattern": "some_crazy_regexp"}},
   "type": "object",
   "properties": {
     "v": {
       "$ref": "definitions/uuid"
     }
   }
 }

**Comment by manycoding** [comment]
To have `format` working, you need to install `spidermon[validation]` https://github.com/scrapinghub/spidermon/blob/master/setup.py#L33.

**Comment by andrewbaxter** [comment]
Oh awesome, thanks!  I'll try it out.  That sounds like my issue with format.

I'd like to keep this open though as a feature request for support validating non-stringified classes.

**Comment by manycoding** [comment]
@andrewbaxter I created #168 , but the original issue with datetime I believe is closed.
